#!/bin/bash
# Wrapper script to run Gradle with Java 17
# This script sets JAVA_HOME before running Gradle to ensure Java 17 is used
export JAVA_HOME=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home
export PATH="$JAVA_HOME/bin:$PATH"
exec ./gradlew "$@"

